config/routes.rb
Rails.application.routes.draw do
  

  get 'welcome/index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  
  resources :articles do
    resources :comments
  end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
  	                  :length => { :minimum => 5}
  validates :text, presence: true,
                    :length => { :minimum => 10}
 end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base

  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_attached_file :avatar, :styles => { 
    :medium => "300x300>", 
    :thumb => "100x100>", 
    :icon => "50x50"}, 
    :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  private
  def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
 end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	# http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
	
	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)
		
		if @article.save
		redirect_to @article
	else
		render 'new'
	end
end

    def update
    	@article = Article.find(params[:id])

    	if @article.update(article_params)
    		redirect_to @article
    	else
    		render 'edit'
    	end
    end

    def destroy
    	@article = Article.find(params[:id])
    	@article.destroy

    	redirect_to articles_path
    end


private
  def article_params
  	params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
end

def create
  user = User.authenticate(params[:user][:email], params[:user][:password])
  if user
    session[:user_id] = user.id
    redirect_to articles_url, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid email or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all 
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :alert => "Signed up!"
    else
      render "new"
    end
  end

private
def user_params
    params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <div class='col-md-10 col-offset-1 text-center'>
  <p class='lead'>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p class='lead'>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit 'Create Article' %>
  </p>
 </div> 
<% end %>

app/views/articles/edit.html.erb
<div class='col-md-10 col-md-offset-1 text-center'>
<h1>Edit Your Review or Article!</h1>


<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    </div>
    <% end %>
  <% end %>
 

  <%= render 'form' %>
 
 <div class='col-md-10 col-md-offset-1 text-center'>
<button type='button' class='btn btn-warning'><%= link_to 'Back', articles_path %></button>
</div>

app/views/articles/index.html.erb
<div class='col-md-10 col-md-offset-1 text-center'>
<h1>Listing of Reviews & Articles </h1>
</div>
<div class = 'col-md-10 col-md-offset-1 text-center'> 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
    <!-- <div class='row well'> -->
    <p class='lead'>
      <td><div class='col-md-6'><%= article.title %></td></div>
      <td><div class='col-md-6'><%= article.text %></td></div>
      </p>
  <!-- </div> -->
      <td><button type='button' class='btn btn-default btn-sm'><%= link_to 'Show', article_path(article) %></td></button>
      <td><button type='button' class='btn btn-info btn-sm'><%= link_to 'Edit', edit_article_path(article) %></td></button>
      <td><button type='button' class='btn btn-danger btn-sm'><%=link_to 'Destroy', article_path(article),
              method: :delete,
              data: {confirm: 'Are you sure?!'} %></td></button>
    </tr>

  <% end %>
<button type='button' class='btn btn-warning'><%= link_to 'New article', new_article_path %></button>

</table>
</div>
</div>

app/views/articles/new.html.erb
<div class='col-md-10 col-offset-1 text-center'>
<h1>New Review!</h1>
</div>
<%= form_for :article, url: articles_path do |f| %>
<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= render 'form' %>
<div class='col-md-10 col-offset-1 text-center'>
<button type='button' class='btn btn-warning'><%= link_to 'Back', articles_path %></button>
</div>
<% end %>

app/views/articles/show.html.erb
<div class='row well well-lg'>
<div class='col-md-6 col-offset-4 text-center'>
<p class='lead'>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p class='lead'>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
</div>
</div> 
<div class='col-md-10 md-offset-1 text-center'>
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<button type='btn' class='btn btn-warning'><%= link_to 'Edit Article', edit_article_path(@article) %> </button>
<button type='btn' class='btn btn-default'><%= link_to 'Back to Articles', articles_path %></button>
</div> 

app/views/comments/_comment.html.erb
<div class='container'>
<div class='col-md-10 col-offset-1 text-center'>
<p class='lead'>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p class='lead'>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
</div>
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
</div>

app/views/comments/_form.html.erb
<div class='container'>
<%= form_for([@article, @article.comments.build]) do |f| %>
<div class='col-md-10 col-offset-1 text-center'>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
   </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScubaCentral</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'></script>
 


</head>
<body>



<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<div class='col-md-10 col-md-offset-1 text-center'>
 <h1>Scuba Central Members</h1>

  </div>
<div class = 'col-md-10 col-md-offset-1 text-center'> 
<table>
<p class='lead'>
  <tr>
    <th>Username</th>
    \<th>Avatar</th>
    <th colspan="2"></th>
  </tr>
 </p>
  <% @users.each do |user| %>
    <tr>
    
    <p class='lead'>
      <td><p class='lead'><div class='col-md-6'><p class='lead'><%= user.username %></td></div></p>
      <td><div class='col-md-6'><p class='lead'><%= image_tag user.avatar.url(:thumb) %></td></div></p>
      </p>      
    </tr>

  <% end %>
  </table>


<button type='button' class='btn btn-warning'><%= link_to 'Reviews', articles_path %></button>
</div>
</div>

app/views/users/new.html.erb
<div class='col-md-10 col-md-offset-1 text-center'>
<h1>Sign Up for Scuba Central</h1>
</div>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
   
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
   
  <% end %>
  
 <div class='col-md-8 col-md-offset-2 text-center'> 
 <p class='lead'>
 <%= f.label :username %><br />
 <%= f.text_field :username %>
 </p>
  <p class='lead'>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p class='lead'>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  
  <p class='lead'>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="lead">
  <%= f.file_field :avatar %>
  </p>
  <p><button><%= f.submit 'Create Account' %></p></button>
<% end %>

</div>
 

app/views/welcome/index.html.erb
<body>
<div class='col-md-10 col-md-offset-1 text-center'>
 <h1>Welcome to Scuba Central!</h1>

  </div>
  <div class='container'>

 
    <div class='col-md-12 text-center'>
    <h2>The site for all your Scuba needs!</h2>

<div id="carousel-example-generic" class="carousel slide fluid col-md-12 hidden-sm hidden-xs" data-ride="carousel" style="height:300px;width:100%">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="http://www.divetime.com/images/photos/assets/5/55115-work-_DJH5238.jpg" style="width:100%;height:300px">
      
    </div>
    <div class="item">
      <img src="http://weekendreviewkit.com/wp-content/uploads/2015/01/Cuddly_Cuttlefish_by_zhe_universe.jpg" style="width:100%;height:300px">
      
    </div>

    <div class="item">
      <img src="http://www.sheratonkona.com/images/main_pics/manta-in-ocean.jpg" style:"width:100%;height:300px">
      
    </div>
    
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


       <p class="lead">Review equipment! Post photos! Make a blog!</br>
       Check the tides! Check the surf! Plan your trip!
       </p>
       <button type='button' class='btn btn-info btn-md'><%= link_to 'Sign In', new_session_path %></button>
       <button type='button' class='btn btn-warning btn-lg'><%= link_to 'Sign Up', new_user_path %></button>
    </div>
  </div>



</body>

 